### ISSUE TITLE
Support for ECS Fargate Spot Jobs and potentially AWS Batch ?

### ISSUE THREAD

**Issue by yuriy-yarosh** [whywaita/shoes-aws#4]
It would be nice to autoscale the Github Actions with the pre-existing AWS Batch job queue integration and target ECS Fargate Spot instances...

Adding ECS Fargate Spot instead of EC2 would also be a good option, as well.

Not sure if Github Actions has a topo-sort algorithm, and a public API, to count the number of parallel jobs at the specific deps tree layer. The number of Batch Queues should match the number of dep tree layers to keep things consistent and simplify the respective abstractions.

**Comment by whywaita** [comment]
Hi @yuriy-yarosh 

I developed [shoes-ecs-task](https://github.com/whywaita/shoes-ecs-task). It's a provider for ECS Fargate. [here](https://github.com/whywaita/shoes-ecs-task/blob/dd9793e279f72778184c52073610264af82c9fac/main.go#L155)
And [shoes-ecs-task's example](https://github.com/whywaita/shoes-ecs-task/blob/dd9793e279f72778184c52073610264af82c9fac/examples/terraform/main.tf#L32) is using fargate_spot.

Could you check this one?

**Comment by yuriy-yarosh** [comment]
Thank you, @whywaita.
I don't really get how it'll be autoscaled.
GH Actions [Webhooks-based autoscaling](https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/autoscaling-with-self-hosted-runners#using-webhooks-for-autoscaling) creates a vendor lock-in, which is not suitable for a lot of companies.

I've been looking into a way of proper autoscaling by using previously run tasks' resource consumption metrics as a foundation of container limit/requests. E.g. ecs/fargate does not provide anything like [vpa recommender](https://github.com/kubernetes/autoscaler/blob/master/vertical-pod-autoscaler/pkg/recommender/README.md) or [goldilocks](https://github.com/FairwindsOps/goldilocks), to trim down overprovisioned resources, so it would make sense to make an AWS Native CloudWatch based recommender instead.

The common AWS EventBridge / StepFunctions / Batch stack can be used to describe the respective CI jobs graph and tasks queue, and schedule the workloads without the need of a static observer (or forever running lambda).

[I'm looking into](https://github.com/nektos/act/issues/2357) how [act](https://github.com/nektos/act) can be redesigned or enhanced rn.
It has a [workflow model](https://github.com/nektos/act/blob/master/pkg/model/workflow.go), but nothing similar to an external workflow or external execution environments providers.

Shoes has the upper hand on that one... although I'm not a huge fan of hashicorp plugins after the tf controversy. 

Feel free to close this.

**Comment by whywaita** [comment]
Thank you 😊
